language: node_js

notifications:
  email:
    recipients:
      - quentin.richard@etu.utc.fr

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS informi_test;'
  - mysql -u root informi_test < ./db.sql

branches:
  only:
    - master
    - /v\d+.\d+(\.d+)?(-[a-zA-Z0-9]+)?/

git:
  depth: 2
